param([ValidateSet('Rapide','Approfondie')][string]$Mode='Rapide')
$ErrorActionPreference='SilentlyContinue';$signature='FDMAHY_TP_SYSTEM';$usbRoot=Split-Path -Parent $MyInvocation.MyCommand.Path
$destination=Join-Path $usbRoot 'TP_RECUPERES';$logDir=Join-Path $usbRoot 'RAPPORTS';New-Item -ItemType Directory -Force -Path $destination,$logDir|Out-Null
$usual=@([Environment]::GetFolderPath('MyDocuments'),[Environment]::GetFolderPath('Desktop'),(Join-Path $env:USERPROFILE 'Downloads'),(Join-Path $env:USERPROFILE 'Documents\TP'),(Join-Path $env:LOCALAPPDATA 'Lecteur_TP_Eleve'))
$roots=if($Mode -eq 'Approfondie'){@($env:USERPROFILE)}else{@($usual|Where-Object{$_ -and (Test-Path -LiteralPath $_)})}
$files=foreach($root in ($roots|Select-Object -Unique)){Get-ChildItem -LiteralPath $root -File -Recurse -Include *.json,*.tp -ErrorAction SilentlyContinue|Where-Object{$_.Length -lt 52428800}}
$found=0;$copied=0;$duplicates=0;$errors=0;$details=@()
foreach($file in ($files|Sort-Object FullName -Unique)){try{$raw=[IO.File]::ReadAllText($file.FullName,[Text.Encoding]::UTF8);$data=$raw|ConvertFrom-Json;$legacy=($data.type -eq 'tp-eleve' -and $data.code -and $data.titre -and $data.reponses);if($data.signature -ne $signature -and -not $legacy){continue};if($data.statut -ne 'RENDU' -and $data.submission.final -ne $true){continue};$found++;$sha=[BitConverter]::ToString(([Security.Cryptography.SHA256]::Create()).ComputeHash([Text.Encoding]::UTF8.GetBytes($raw))).Replace('-','').ToLower();$nom=if($data.identite.nom){$data.identite.nom}else{$data.eleve.nom};$prenom=if($data.identite.prenom){$data.identite.prenom}else{$data.eleve.prenom};$classe=if($data.identite.classe){$data.identite.classe}else{$data.classe};$titre=if($data.tp.titre){$data.tp.titre}else{$data.titre};$clean={param($v)(($v-replace '[<>:"/\\|?*]','_'-replace '[^a-zA-Z0-9._-]','_').Trim('_','.',' '))};$base=@((&$clean $nom).ToUpper(),(&$clean $prenom),(&$clean $titre),'RENDU')-join '_';$classDir=Join-Path $destination (&$clean $classe);New-Item -ItemType Directory -Force -Path $classDir|Out-Null;$existing=Get-ChildItem -LiteralPath $classDir -File -Filter '*.json'|Where-Object{(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLower() -eq $sha};if($existing){$duplicates++;$details+="DOUBLON : $($file.FullName)";continue};$target=Join-Path $classDir ($base+'.json');$n=2;while(Test-Path -LiteralPath $target){$target=Join-Path $classDir ($base+'_VERSION_'+$n+'.json');$n++};Copy-Item -LiteralPath $file.FullName -Destination $target;$copied++;$details+="COPIE : $($file.FullName) -> $target"}catch{$errors++;$details+="ERREUR : $($file.FullName)"}}
$stamp=Get-Date -Format 'yyyy-MM-dd_HH-mm-ss';$report=Join-Path $logDir ("Rapport_$stamp.txt");@("RECUPERATION TP - $Mode","Date : $(Get-Date -Format 'dd/MM/yyyy HH:mm:ss')","TP trouves : $found","TP copies : $copied","Doublons ignores : $duplicates","Erreurs : $errors",'')+$details|Set-Content -LiteralPath $report -Encoding UTF8
Write-Host '';Write-Host '========================================' -ForegroundColor Cyan;Write-Host "Recuperation terminee : $found TP trouves - $copied TP copies." -ForegroundColor Green;Write-Host "Doublons ignores : $duplicates - Erreurs : $errors";Write-Host "Dossier : $destination";Write-Host "Rapport : $report";Write-Host '========================================' -ForegroundColor Cyan
